<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="striker" name="testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS" tests="3" failures="1" timestamp="26 Oct 2018 12:12:24 GMT" time="119.642" errors="0">
  <testcase name="beforeMethod" time="18.116" classname="testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at utilities.Login.LoginWithAdmin(Login.java:28)
at testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS.beforeMethod(Creating_marketing_EMAIL_SETTINGS.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- beforeMethod -->
  <testcase name="creating_marketing_EMAIL_SETTINGS" time="101.526" classname="testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS">
    <skipped/>
  </testcase> <!-- creating_marketing_EMAIL_SETTINGS -->
  <testcase name="creating_marketing_EMAIL_SETTINGS" time="0.000" classname="testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS">
    <skipped/>
  </testcase> <!-- creating_marketing_EMAIL_SETTINGS -->
</testsuite> <!-- testCases.Home.ProjectSetUp.Creating_marketing_EMAIL_SETTINGS -->
